### ISSUE TITLE
not actually published to bower

### ISSUE THREAD

**Issue by michaelficarra** [dicefm/purescript-node-redis#3]
The `purescript-node-redis` package is not registered with bower, and this repo has no tags.

```
$ bower install --save purescript-node-redis
bower ENOTFOUND     Package purescript-node-redis not found
```

**Comment by SimonRichardson** [comment]
I've not had time to finish this, I can release in it's current state, but it's got about 4 commands, hence why I haven't released it yet.

Also I'm working on a better release in the commands branch #2, I'm about 50% done on this.

**Comment by michaelficarra** [comment]
I saw that branch, it was looking good. I was just pointing out that it says to install it using that name on bower and that doesn't work.

**Comment by SimonRichardson** [comment]
@michaelficarra you spurred me to start back on it :+1: 

I've added it to bower.

**Comment by michaelficarra** [comment]
I have trouble building the version published to bower. I'm getting the error

```
Error in module Database.Redis.Redis:
Error at bower_components/purescript-node-redis/src/Database/Redis/Redis.purs line 53, column 8 - line 53, column 23:
  Unknown value parseFileURI
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue for more information, or to contribute content related to this error.
```

**Comment by SimonRichardson** [comment]
@michaelficarra I've managed to update the master branch. It's now using the commands. Note that it uses pipelining be default, which is what we wanted to use, it wouldn't be too difficult to not do this I guess, but pipelining gives the ability to pipe multiple queries to the redis instance.

consider:

``` purescript
commands :: Query
commands = do
  set (name "list") "hello"
  get $ name "list"  
  mset [tuple2 (name "x") "y", tuple2 (name "a") "b"]
  mget [name "x", name "a"]
```

**Comment by paf31** [comment]
:cool:

**Comment by michaelficarra** [comment]
@SimonRichardson I don't see any git tags. Is that why you've re-opened?

**Comment by SimonRichardson** [comment]
Yeah, I'm not happy to release this until #5 is done.

**Comment by SimonRichardson** [comment]
I've created an initial release, I'll start implementing more commands soon.
