### ISSUE TITLE
provide a way to select a database

### ISSUE THREAD

**Issue by michaelficarra** [dicefm/purescript-node-redis#7]
Selecting a database is technically added through [a command](http://redis.io/commands/select), but I would like us to conceptualise it as a connect (`connect'`?) parameter.

**Comment by SimonRichardson** [comment]
`redis://127.0.0.1:6379/0`

Turns out you can already do this via the uri, is this enough? The library supports it out of the box[1]
[1] https://github.com/luin/ioredis/blob/master/lib/utils/index.js#L272

**Comment by michaelficarra** [comment]
Oh, I didn't know about this. That should suffice for now. Thanks.
